'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsComment
    Inherits DataSet
    
    Private tableComment As CommentDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Comment")) Is Nothing) Then
                Me.Tables.Add(New CommentDataTable(ds.Tables("Comment")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Comment As CommentDataTable
        Get
            Return Me.tableComment
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsComment = CType(MyBase.Clone,dsComment)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Comment")) Is Nothing) Then
            Me.Tables.Add(New CommentDataTable(ds.Tables("Comment")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableComment = CType(Me.Tables("Comment"),CommentDataTable)
        If (Not (Me.tableComment) Is Nothing) Then
            Me.tableComment.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsComment"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsComment.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-ZA")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableComment = New CommentDataTable
        Me.Tables.Add(Me.tableComment)
    End Sub
    
    Private Function ShouldSerializeComment() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub CommentRowChangeEventHandler(ByVal sender As Object, ByVal e As CommentRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CommentDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnid As DataColumn
        
        Private columnCaseId As DataColumn
        
        Private columnNote As DataColumn
        
        Private columnNoteDate As DataColumn
        
        Private columnNoteUsr As DataColumn
        
        Friend Sub New()
            MyBase.New("Comment")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property idColumn As DataColumn
            Get
                Return Me.columnid
            End Get
        End Property
        
        Friend ReadOnly Property CaseIdColumn As DataColumn
            Get
                Return Me.columnCaseId
            End Get
        End Property
        
        Friend ReadOnly Property NoteColumn As DataColumn
            Get
                Return Me.columnNote
            End Get
        End Property
        
        Friend ReadOnly Property NoteDateColumn As DataColumn
            Get
                Return Me.columnNoteDate
            End Get
        End Property
        
        Friend ReadOnly Property NoteUsrColumn As DataColumn
            Get
                Return Me.columnNoteUsr
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As CommentRow
            Get
                Return CType(Me.Rows(index),CommentRow)
            End Get
        End Property
        
        Public Event CommentRowChanged As CommentRowChangeEventHandler
        
        Public Event CommentRowChanging As CommentRowChangeEventHandler
        
        Public Event CommentRowDeleted As CommentRowChangeEventHandler
        
        Public Event CommentRowDeleting As CommentRowChangeEventHandler
        
        Public Overloads Sub AddCommentRow(ByVal row As CommentRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddCommentRow(ByVal id As Integer, ByVal CaseId As Integer, ByVal Note As String, ByVal NoteDate As String, ByVal NoteUsr As String) As CommentRow
            Dim rowCommentRow As CommentRow = CType(Me.NewRow,CommentRow)
            rowCommentRow.ItemArray = New Object() {id, CaseId, Note, NoteDate, NoteUsr}
            Me.Rows.Add(rowCommentRow)
            Return rowCommentRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As CommentDataTable = CType(MyBase.Clone,CommentDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New CommentDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnid = Me.Columns("id")
            Me.columnCaseId = Me.Columns("CaseId")
            Me.columnNote = Me.Columns("Note")
            Me.columnNoteDate = Me.Columns("NoteDate")
            Me.columnNoteUsr = Me.Columns("NoteUsr")
        End Sub
        
        Private Sub InitClass()
            Me.columnid = New DataColumn("id", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnid)
            Me.columnCaseId = New DataColumn("CaseId", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCaseId)
            Me.columnNote = New DataColumn("Note", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNote)
            Me.columnNoteDate = New DataColumn("NoteDate", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNoteDate)
            Me.columnNoteUsr = New DataColumn("NoteUsr", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnNoteUsr)
        End Sub
        
        Public Function NewCommentRow() As CommentRow
            Return CType(Me.NewRow,CommentRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New CommentRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(CommentRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.CommentRowChangedEvent) Is Nothing) Then
                RaiseEvent CommentRowChanged(Me, New CommentRowChangeEvent(CType(e.Row,CommentRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.CommentRowChangingEvent) Is Nothing) Then
                RaiseEvent CommentRowChanging(Me, New CommentRowChangeEvent(CType(e.Row,CommentRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.CommentRowDeletedEvent) Is Nothing) Then
                RaiseEvent CommentRowDeleted(Me, New CommentRowChangeEvent(CType(e.Row,CommentRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.CommentRowDeletingEvent) Is Nothing) Then
                RaiseEvent CommentRowDeleting(Me, New CommentRowChangeEvent(CType(e.Row,CommentRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveCommentRow(ByVal row As CommentRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CommentRow
        Inherits DataRow
        
        Private tableComment As CommentDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableComment = CType(Me.Table,CommentDataTable)
        End Sub
        
        Public Property id As Integer
            Get
                Try 
                    Return CType(Me(Me.tableComment.idColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableComment.idColumn) = value
            End Set
        End Property
        
        Public Property CaseId As Integer
            Get
                Try 
                    Return CType(Me(Me.tableComment.CaseIdColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableComment.CaseIdColumn) = value
            End Set
        End Property
        
        Public Property Note As String
            Get
                Try 
                    Return CType(Me(Me.tableComment.NoteColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableComment.NoteColumn) = value
            End Set
        End Property
        
        Public Property NoteDate As String
            Get
                Try 
                    Return CType(Me(Me.tableComment.NoteDateColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableComment.NoteDateColumn) = value
            End Set
        End Property
        
        Public Property NoteUsr As String
            Get
                Try 
                    Return CType(Me(Me.tableComment.NoteUsrColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableComment.NoteUsrColumn) = value
            End Set
        End Property
        
        Public Function IsidNull() As Boolean
            Return Me.IsNull(Me.tableComment.idColumn)
        End Function
        
        Public Sub SetidNull()
            Me(Me.tableComment.idColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCaseIdNull() As Boolean
            Return Me.IsNull(Me.tableComment.CaseIdColumn)
        End Function
        
        Public Sub SetCaseIdNull()
            Me(Me.tableComment.CaseIdColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNoteNull() As Boolean
            Return Me.IsNull(Me.tableComment.NoteColumn)
        End Function
        
        Public Sub SetNoteNull()
            Me(Me.tableComment.NoteColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNoteDateNull() As Boolean
            Return Me.IsNull(Me.tableComment.NoteDateColumn)
        End Function
        
        Public Sub SetNoteDateNull()
            Me(Me.tableComment.NoteDateColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsNoteUsrNull() As Boolean
            Return Me.IsNull(Me.tableComment.NoteUsrColumn)
        End Function
        
        Public Sub SetNoteUsrNull()
            Me(Me.tableComment.NoteUsrColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CommentRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As CommentRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As CommentRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As CommentRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
