'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace wsMindKey
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PrimaryServiceEntrySoap", [Namespace]:="http://www.Orion.net/webservices")>  _
    Public Class PrimaryServiceEntry
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Public SecurityContextValue As SecurityContext
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://fnetwebtest/mindkeywf/mindkeywf.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Orion.net/webservices/ServiceImageRequest", RequestNamespace:="http://www.Orion.net/webservices", ResponseNamespace:="http://www.Orion.net/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ServiceImageRequest(ByVal XMLInstruction As String) As <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> Byte()
            Dim results() As Object = Me.Invoke("ServiceImageRequest", New Object() {XMLInstruction})
            Return CType(results(0),Byte())
        End Function
        
        '<remarks/>
        Public Function BeginServiceImageRequest(ByVal XMLInstruction As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ServiceImageRequest", New Object() {XMLInstruction}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndServiceImageRequest(ByVal asyncResult As System.IAsyncResult) As Byte()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Byte())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapHeaderAttribute("SecurityContextValue"),  _
         System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.Orion.net/webservices/ServiceRequest", RequestNamespace:="http://www.Orion.net/webservices", ResponseNamespace:="http://www.Orion.net/webservices", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ServiceRequest(ByVal XMLInstruction As String) As String
            Dim results() As Object = Me.Invoke("ServiceRequest", New Object() {XMLInstruction})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginServiceRequest(ByVal XMLInstruction As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ServiceRequest", New Object() {XMLInstruction}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndServiceRequest(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.Orion.net/webservices"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.Orion.net/webservices", IsNullable:=false)>  _
    Public Class SecurityContext
        Inherits System.Web.Services.Protocols.SoapHeader
        
        '<remarks/>
        Public ContextXML As String
    End Class
End Namespace
